name: Build

on:
    push:
        branches:
                - '*'
    schedule:
        - cron: "0 0 * * 1,4"  # Run at midnight on Monday and Thursday

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
                - name: Checkout code
                  uses: actions/checkout@v2

                - name: Cache Rust dependencies
                  uses: actions/cache@v2
                  with:
                                path: ~/.cargo
                                key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
                                restore-keys: ${{ runner.os }}-rust-

                - name: Install Yarn
                  run: npm install -g yarn

                - name: Cache Yarn dependencies
                  uses: actions/cache@v2
                  with:
                    path: ~/.yarn
                    key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: ${{ runner.os }}-yarn-

                - name: Install Rust
                  uses: actions-rs/toolchain@v1
                  with:
                    toolchain: stable
                    components: rustfmt, clippy

                - name: Install Make
                  run: sudo apt-get install make

                - name: Set up wasm-unknown-unknown target
                  run: rustup target add wasm32-unknown-unknown

                - name: Build using Make
                  run: |
                        make setup
                        make build
